"use client";

import { useMemo, useState } from "react";

type Entry = {
  name: string; org: string; url: string; kind: string; category: string;
  tier: string; tierLabel: string; stars: number; lastPush: string;
  daysSincePush: number; stale: boolean; dataSources: string[]; tags: string[];
  summary: string; note: string | null;
  verification: {
    status: string; verifiedAt: string; repositoryStatus: string;
    canonicalRepository?: string; publisherClassification?: string;
    license?: string; defaultBranch?: string; forks?: number; openIssues?: number;
    officialRegistryListed: boolean; officialRegistryName?: string | null;
    officialRegistryVersion?: string | null; officialRegistryStatus?: string | null;
    verificationSources: string[]; note: string;
  };
};

const tierCopy: Record<string, { label: string; description: string }> = {
  "1": { label: "Provenanced", description: "Institutional, consortium, or known author" },
  "2": { label: "Active", description: "Maintained, coherent scope, unaffiliated" },
  "3": { label: "Unreviewed", description: "Indexed, not assessed" },
  F: { label: "Flagged", description: "Verify carefully before use" },
};

const formatDate = (date: string) => new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" }).format(new Date(`${date}T00:00:00Z`));

export function RegistryExplorer() {
  const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

  return (
    <main>
      <header className="site-header">
        <a className="brand" href="https://blackswancausallabs.com" aria-label="Black Swan Causal Labs home">
          <span>BLACK SWAN <b>CAUSAL LABS</b></span>
        </a>
        <nav aria-label="Primary navigation">
          <a href="#registry">Registry</a><a href={`${basePath}/methods/`}>Methods</a><a href={`${basePath}/faq/`}>FAQ</a>
        </nav>
      </header>

      <section className="hero">
        <div className="hero-grid">
          <div>
            <h1>The RWE<br /><i>MCP Registry</i></h1>
            <p className="lede">A source-reviewed catalogue of MCP servers, skills, libraries, and agents for real-world evidence workflows.</p>
          </div>
          <div className="update-stamp" aria-label="Registry update schedule">
            <strong>Updated<br />weekly</strong>
            <span>Last reviewed</span>
            <time dateTime="2026-07-23">Jul 23, 2026</time>
          </div>
        </div>
        <div className="signal-line" aria-hidden="true" />
      </section>

      <section className="registry" id="registry">
        <CardPrototype />

        <aside className="coverage-note" aria-label="Registry coverage boundary">
          <p><strong>This index covers publicly discoverable work only.</strong> Private repositories, internal enterprise servers, unpublished skills, and public projects that are not registered, indexed, or documented cannot be observed. An absent capability means “not found in the searched public sources,” not “does not exist.”</p>
          <a href="/methods#coverage">How coverage is defined ↗</a>
        </aside>

      </section>

      <footer><p>© 2026 Black Swan Causal Labs</p><p><a href="https://blackswancausallabs.com/#contact">Suggest an addition ↗</a></p></footer>
    </main>
  );
}

const prototypeCards = [
  { name:"bioSkills", kind:"Skill collection", category:"Trials & Study Design", summary:"Bioinformatics skill collection with an RWE-relevant clinical-biostatistics component.", tags:["Clinical biostatistics","Survival analysis","Study design"], added:"Jul 11, 2026", checked:"Jul 23, 2026", status:"Static documentation reviewed", runtime:"Not runtime tested", repository:"GPTomics/bioSkills", website:"GitHub", packages:"Clinical-biostatistics component", workflowFit:["Analysis planning","Statistical programming","Reproducible workflow guidance"], capabilities:["Selective skill-category installation","Clinical-biostatistics methods guidance","Survival, estimand, missing-data, and trial-design skills"], limitation:"Capabilities are attributed to the clinical-biostatistics component, not the entire collection. Generated code and method choices require independent review.", url:"https://github.com/GPTomics/bioSkills" },
  { name:"HEORAgent MCP Server", kind:"MCP server", category:"Literature & Evidence Synthesis", summary:"HEOR-oriented MCP server documenting evidence synthesis, economic modeling, HTA, RWE, and pharmacovigilance workflows.", tags:["HEOR","Economic modeling","HTA"], added:"Jul 12, 2026", checked:"Jul 23, 2026", status:"Static implementation reviewed", runtime:"Not runtime tested", repository:"neptun2000/heor-agent-mcp", website:"npm", packages:"heor-agent-mcp 1.27.0", workflowFit:["Evidence synthesis","Cost-effectiveness and budget impact","HTA preparation"], capabilities:["Multi-source literature and bias assessment","Economic and indirect-comparison modeling","HTA dossier and RWE method workflows"], limitation:"The broad, decision-grade tool surface requires tool-by-tool runtime and methodological validation. Outputs are not substitutes for independent HEOR or regulatory review.", url:"https://github.com/neptun2000/heor-agent-mcp" },
  { name:"paper-mcp", kind:"MCP server", category:"Literature & Evidence Synthesis", summary:"Scholarly-search server combining medical-evidence retrieval, citation exploration, and PDF/LaTeX utilities.", tags:["PubMed / Europe PMC","Citation graphs","PDF extraction"], added:"Jul 12, 2026", checked:"Jul 23, 2026", status:"Static implementation reviewed", runtime:"Not runtime tested", repository:"MCPServings/paper-mcp", website:"GitHub", packages:"paper-mcp 0.5.0", workflowFit:["Literature discovery","Citation chaining","Evidence retrieval"], capabilities:["PubMed and Europe PMC evidence search","Semantic Scholar and OpenAlex citation tools","Paper fetch, full text, and optional PDF extraction"], limitation:"Coverage, evidence-grading logic, full-text licensing, credentials, and citation accuracy require separate testing; some optional utilities use external services.", url:"https://github.com/MCPServings/paper-mcp" },
  { name:"paper-search-mcp-openai", kind:"MCP server", category:"Literature & Evidence Synthesis", summary:"Multi-source scholarly search and retrieval across PubMed, preprints, indexes, and citation services.", tags:["PubMed","Multi-source search","Full text"], added:"Jul 12, 2026", checked:"Jul 23, 2026", status:"Static implementation reviewed", runtime:"Not runtime tested", repository:"adamamer20/paper-search-mcp-openai", website:"GitHub", packages:"paper-search-mcp 0.1.3", workflowFit:["Literature discovery","Evidence scoping","Citation chasing"], capabilities:["Unified search and fetch","Source-specific search and download","PubMed, preprint, Semantic Scholar, and Crossref support"], limitation:"Provider coverage and full-text availability vary; reproducible reviews still require logged queries, dates, deduplication, and primary-source verification.", url:"https://github.com/adamamer20/paper-search-mcp-openai" },
  { name:"pubmed-mcp-smithery", kind:"MCP server", category:"Literature & Evidence Synthesis", summary:"PubMed server with keyword, MeSH, publication-count, article-detail, and PICO-oriented search tools.", tags:["PubMed","MeSH","PICO search"], added:"Jul 12, 2026", checked:"Jul 23, 2026", status:"Static implementation reviewed · caveat", runtime:"Not runtime tested", repository:"lineex/pubmed-mcp-smithery", website:"Smithery", packages:"Source script", workflowFit:["Search strategy development","Literature discovery","Evidence scoping"], capabilities:["Keyword and journal search","MeSH and PMID detail retrieval","PICO combination searches"], limitation:"No package manifest or license file was found; PICO query generation is not a systematic review and NCBI rate-limit behavior remains untested.", url:"https://github.com/lineex/pubmed-mcp-smithery" },
  { name:"bq-health-mcp", kind:"MCP server", category:"OMOP & terminology", summary:"Read-only structured exploration of a public synthetic OMOP observation table in BigQuery.", tags:["BigQuery","OMOP observation","Synthetic data"], added:"Jul 12, 2026", checked:"Jul 23, 2026", status:"Static implementation reviewed · caveat", runtime:"Not runtime tested", repository:"a-xp/bq-health-mcp", website:"GitHub", packages:"bq-health-mcp 0.1.0", workflowFit:["Data exploration","Feasibility prototyping","Concept-frequency review"], capabilities:["Filtered observation queries","Aggregate statistics and frequent concepts","Person-level synthetic timelines"], limitation:"It targets one synthetic observation table, not a complete production CDM; stronger SQL verification, authorization, and usage limits remain TODOs.", url:"https://github.com/a-xp/bq-health-mcp" },
  { name:"OHDSI MCPs", kind:"MCP collection", category:"OMOP & terminology", summary:"Hosted reference servers for the Book of OHDSI, OMOP CDM specifications, and the OHDSI Weekly Digest.", tags:["OMOP CDM docs","Book of OHDSI","Weekly digest"], added:"Jul 12, 2026", checked:"Jul 23, 2026", status:"Static documentation reviewed", runtime:"Not runtime tested", repository:"Leko/ohdsi-mcps", website:"Hosted endpoints", packages:"Three component servers", workflowFit:["Standards reference","Methods orientation","Community monitoring"], capabilities:["Chapter reading and search","CDM table and field reference","Weekly Digest retrieval"], limitation:"These are reference and community-content services—not patient-data access or vocabulary lookup. Claims must retain component and upstream-source attribution.", url:"https://github.com/Leko/ohdsi-mcps" },
  { name:"ohdsi-webapi-mcp", kind:"MCP server", category:"OMOP & terminology", summary:"OHDSI WebAPI bridge for vocabulary discovery, cohort construction, persistence, and feasibility estimation.", tags:["OHDSI WebAPI","Cohort definitions","Concept sets"], added:"Jul 12, 2026", checked:"Jul 23, 2026", status:"Static implementation reviewed · write scope", runtime:"Not runtime tested", repository:"clsweeting/ohdsi-webapi-mcp", website:"GitHub", packages:"ohdsi-webapi-mcp 0.2.1", workflowFit:["Cohort design","Feasibility estimation","Vocabulary navigation"], capabilities:["Concept and hierarchy tools","Cohort criteria and validation","Persistence, comparison, and job control"], limitation:"It can save or clone cohort definitions and cancel jobs. Authorization inherits the target WebAPI deployment and was not established by this review.", url:"https://github.com/clsweeting/ohdsi-webapi-mcp" },
  { name:"OMOP MCP Server", kind:"MCP server", category:"OMOP & terminology", summary:"OHNLP terminology-mapping server using an LLM and OMOPHub vocabulary services.", tags:["Terminology mapping","OMOP concepts","Batch mapping"], added:"Jul 12, 2026", checked:"Jul 23, 2026", status:"Static implementation reviewed · validation priority", runtime:"Not runtime tested", repository:"OHNLP/omop_mcp", website:"OMapper demo", packages:"omop_mcp 0.2.0", workflowFit:["Source-to-standard mapping","Vocabulary search","Harmonization preparation"], capabilities:["Contextual concept lookup","CSV batch mapping","Preferred-vocabulary guidance"], limitation:"LLM- and API-derived mappings require authoritative vocabulary-version checks and human review; batch mapping also reads and writes local files.", url:"https://github.com/OHNLP/omop_mcp" },
  { name:"OMOPHub MCP Server", kind:"MCP server", category:"OMOP & terminology", summary:"Search, map, validate, and navigate OMOP concepts across clinical coding systems.", tags:["Vocabulary search","Crosswalks","FHIR resolution"], added:"Jul 12, 2026", checked:"Jul 23, 2026", status:"Static documentation rechecked", runtime:"Not runtime tested", repository:"OMOPHub/omophub-mcp", website:"omophub.com", packages:"@omophub/omophub-mcp 1.5.3", workflowFit:["Terminology normalization","Concept-set development","Code validation"], capabilities:["Concept lookup, semantic search, and code validation","Cross-vocabulary mapping and hierarchy navigation","FHIR coded-value and CodeableConcept resolution to OMOP targets"], limitation:"Results depend on API availability, service coverage, vocabulary versions, and authentication. Mapping, hierarchy expansion, FHIR resolution, and generated concept sets still require study-specific review.", url:"https://github.com/OMOPHub/omophub-mcp" },
  { name:"pyomop", kind:"Library + MCP server", category:"OMOP & terminology", summary:"Python OMOP toolkit with database management, FHIR import, QueryLibrary execution, and MCP interfaces.", tags:["OMOP CDM","FHIR import","SQL execution"], added:"Jul 12, 2026", checked:"Jul 23, 2026", status:"Static documentation rechecked · high-risk SQL", runtime:"Not runtime tested", repository:"dermatologist/pyomop", website:"Documentation", packages:"pyomop 6.4.0", workflowFit:["Data-model prototyping","ETL experimentation","OMOP query tooling"], capabilities:["OMOP v5.4/v6 models and schema inspection","FHIR Bulk Export conversion and QueryLibrary examples","SQL validation/execution plus stdio and HTTP MCP transports"], limitation:"The MCP surface executes caller-supplied SQL. Database credentials, least privilege, PHI controls, query review, and write isolation remain essential; create_cdm and create_eunomia are documented as restricted to local SQLite.", url:"https://github.com/dermatologist/pyomop" },
  { name:"UCSFOMOPAgent", kind:"MCP server", category:"OMOP & terminology", summary:"Credentialed read-only access to UCSF’s de-identified OMOP CDM with schema, concept, and lab helpers.", tags:["De-identified EHR","OMOP querying","Phenotyping"], added:"Jul 12, 2026", checked:"Jul 23, 2026", status:"Static implementation reviewed · restricted deployment", runtime:"Not runtime tested", repository:"BaranziniLab/UCSFOMOPAgent", website:"GitHub", packages:"ucsfomopagent 0.2.0", workflowFit:["Cohort feasibility","Phenotype exploration","Clinical-data retrieval"], capabilities:["Validated read-only T-SQL","Live schema and concept search","Measurement concept resolution"], limitation:"It is institution-specific and returns row-level de-identified data; disclosure risk, credentials, query validation, and benchmark claims require UCSF governance review.", url:"https://github.com/BaranziniLab/UCSFOMOPAgent" },
  { name:"WebApiMcp", kind:"MCP server", category:"OMOP & terminology", summary:"Read-oriented OHDSI WebAPI wrapper for concepts, sources, cohort definitions, and concept sets.", tags:["OHDSI WebAPI","Cohort definitions","Concept sets"], added:"Jul 12, 2026", checked:"Jul 23, 2026", status:"Static implementation reviewed · caveat", runtime:"Not runtime tested", repository:"schuemie/WebApiMcp", website:"GitHub", packages:"webapi-mcp 0.1.0", workflowFit:["Cohort-definition review","Vocabulary lookup","Source inspection"], capabilities:["Concept search and record counts","Cohort definition retrieval","Concept set retrieval and metadata"], limitation:"Access controls, disclosure thresholds, and compatibility depend on the configured WebAPI deployment; no repository license was declared.", url:"https://github.com/schuemie/WebApiMcp" },
  { name:"SignalBridge for openFDA", kind:"MCP server", category:"Pharmacovigilance & safety", summary:"Structured openFDA access for FAERS exploration, drug labels, listedness, and recall searches.", tags:["FAERS","Drug labels","Recalls"], added:"Jul 12, 2026", checked:"Jul 23, 2026", status:"Static implementation reviewed", runtime:"Not runtime tested", repository:"Janiumang/mcp-server-openfda", website:"GitHub", packages:"mcp-server-openfda 0.1.0", workflowFit:["Safety case exploration","Label review","Regulatory-source retrieval"], capabilities:["Adverse-event search and counts","Drug-label sections","Recall and enforcement searches"], limitation:"openFDA reports do not provide incidence or causality. Reporting bias, duplicate cases, product normalization, truncation, and label versions require qualified PV review.", url:"https://github.com/Janiumang/mcp-server-openfda" },
  { name:"PV Signal MCP Server", kind:"MCP server", category:"Pharmacovigilance & safety", summary:"Stateless PRR and ROR calculator for caller-supplied adverse-event contingency counts.", tags:["PRR","ROR","Disproportionality"], added:"Jul 12, 2026", checked:"Jul 23, 2026", status:"Static implementation reviewed · methods caveat", runtime:"Not runtime tested", repository:"aneesh-sayal-tkd/pharmacovigilance-mcp-server", website:"GitHub", packages:"Source repository", workflowFit:["Signal screening","Contingency-table analysis"], capabilities:["PRR and ROR calculations","ROR confidence interval","Threshold-based ranking"], limitation:"It does not retrieve or validate FAERS data, calculate documented chi-square, apply continuity corrections, or adjust for multiplicity; README and implementation differ.", url:"https://github.com/aneesh-sayal-tkd/pharmacovigilance-mcp-server" },
  { name:"Vigil", kind:"MCP server + A2A agent", category:"Pharmacovigilance & safety", summary:"Workspace adverse-event scanner using BOCPD, Poisson z-score, CUSUM, and signed FHIR outputs.", tags:["Safety surveillance","FHIR DetectedIssue","Change detection"], added:"Jul 12, 2026", checked:"Jul 23, 2026", status:"Static implementation reviewed · validation priority", runtime:"Not runtime tested", repository:"AbhinavGupta707/Vigil", website:"Live demo", packages:"vigil 1.0.0", workflowFit:["Signal detection research","Workspace surveillance","Audit-ready prototyping"], capabilities:["Three-method detection ensemble","Benjamini–Hochberg control","Signed FHIR safety output"], limitation:"Performance is based on engineered frozen corpora, not prospective external validation. Patient-level scanning and FHIR writes require independent statistical, privacy, and clinical review.", url:"https://github.com/AbhinavGupta707/Vigil" },
  { name:"AqtaBio Research", kind:"MCP server + research mirror", category:"Public health & surveillance", summary:"Research-preview MCP for population-level, pre-etiologic zoonotic spillover-risk forecasting at 25 km resolution.", tags:["Spillover forecasting","Hotspots","Disease X"], added:"Jul 12, 2026", checked:"Jul 23, 2026", status:"Static documentation rechecked · research caveat", runtime:"Not runtime tested", repository:"Aqta-ai/aqtabio-research", website:"aqtabio.org", packages:"AqtaBio MCP 0.1.0", workflowFit:["Surveillance prioritization","Preparedness planning","Research forecasting"], capabilities:["Pathogen and Disease X population-risk scoring","Hotspots, trends, briefings, and sentinel-placement recommendations","FHIR R4 outputs, retrospective-validation tooling, and governance metadata"], limitation:"Evaluation is retrospective; aggregate validation and independent replication remain pending. The public research mirror omits production ingestion and trained model artifacts, some mirrored imports do not run independently, and outputs are not cleared for clinical or regulatory use.", url:"https://github.com/Aqta-ai/aqtabio-research" },
  { name:"wonder-mcp", kind:"MCP server", category:"Public health & surveillance", summary:"CDC WONDER querying with preserved request provenance, replication code, and epidemiologic calculations.", tags:["CDC WONDER","Mortality","Reproducible queries"], added:"Jul 12, 2026", checked:"Jul 23, 2026", status:"Static implementation reviewed", runtime:"Not runtime tested", repository:"hesscl/wonder-mcp", website:"CDC WONDER", packages:"wonder-mcp 0.1.0", workflowFit:["Mortality and natality analysis","Population-health surveillance","Reproducible extraction"], capabilities:["WONDER database and variable discovery","Exact XML query preservation","Rate, trend, life-table, and decomposition tools"], limitation:"Suppression, data-use restrictions, provisional data, denominators, and comparability must be preserved; derived calculations require independent methodological checking.", url:"https://github.com/hesscl/wonder-mcp" },
  { name:"DAG Studio MCP", kind:"MCP server", category:"Trials & Study Design", summary:"Causal-DAG server for graph construction, identification checks, adjustment planning, code generation, and simulation-based bias analysis.", tags:["Causal DAGs","Adjustment sets","Bias simulation"], added:"Jul 23, 2026", checked:"Jul 23, 2026", status:"Static implementation and registry metadata reviewed", runtime:"Not independently runtime tested by registry", repository:"Black-Swan-Causal-Labs/dagstudio-mcp", website:"Official MCP Registry", packages:"dag-studio-mcp 0.1.0", workflowFit:["Causal model specification","Covariate-adjustment planning","Bias analysis and methods education"], capabilities:["Backdoor-path and minimal adjustment-set analysis","Overadjustment checks for mediators, colliders, and descendants","Data simulation, empirical bias calculation, and effect-modification classification"], limitation:"Results depend on the correctness and completeness of the user-specified causal graph and structural assumptions. Generated code, concordance checks, and simulated bias do not validate study data, causal assumptions, or fitness for a specific analysis.", favorite:true, url:"https://github.com/Black-Swan-Causal-Labs/dagstudio-mcp" },
  { name:"TARGET Checklist MCP", kind:"MCP server + optional orchestration skill", category:"Trials & Study Design", summary:"TARGET-guideline reporting-completeness assessment for target-trial-emulation manuscripts with evidence-linked checklist outputs.", tags:["Target trial emulation","TARGET guideline","Reporting audit"], added:"Jul 23, 2026", checked:"Jul 23, 2026", status:"Static implementation and registry metadata reviewed", runtime:"Not independently runtime tested by registry", repository:"Black-Swan-Causal-Labs/target-mcp", website:"Official MCP Registry", packages:"target-mcp 0.1.2", workflowFit:["Target-trial-emulation reporting review","Evidence traceability","Corpus-level reporting audit"], capabilities:["Parse manuscripts and available supplements","Assess 39 checklist leaves with resolved evidence spans","Render checklists, coding sheets, corpus summaries, and agreement statistics"], limitation:"The output measures reporting completeness—not study quality, TARGET compliance, causal validity, or a pass/fail verdict. Model-assisted evidence and verdicts require expert review, and full-text or supplement retrieval may be incomplete.", favorite:true, url:"https://github.com/Black-Swan-Causal-Labs/target-mcp" },
  { name:"AWS HealthLake MCP Server", kind:"MCP server", category:"Clinical Data & Interoperability", summary:"AWS-maintained MCP server for discovering HealthLake datastores and managing FHIR resources and import/export jobs.", tags:["AWS HealthLake","FHIR","Read-only mode"], added:"Jul 23, 2026", checked:"Jul 23, 2026", status:"Static implementation and documentation reviewed", runtime:"Not independently runtime tested", repository:"awslabs/mcp · healthlake-mcp-server", website:"GitHub", packages:"awslabs.healthlake-mcp-server", workflowFit:["FHIR cohort and data exploration","Patient-level record retrieval","HealthLake operations review"], capabilities:["11 FHIR tools and automatic datastore discovery","Search, patient-everything, and resource CRUD","Import/export job management and explicit read-only mode"], limitation:"The server can mutate or delete production FHIR data unless read-only mode and least-privilege IAM are enforced. AWS credentials, HealthLake configuration, PHI controls, and query semantics remain deployment responsibilities.", url:"https://github.com/awslabs/mcp/tree/main/src/healthlake-mcp-server" },
  { name:"CharmHealth MCP Server", kind:"MCP server", category:"Clinical Data & Interoperability", summary:"CharmHealth EHR connector exposing patient, encounter, laboratory, medication, messaging, and practice workflows through MCP.", tags:["CharmHealth EHR","Patient records","Clinical workflows"], added:"Jul 23, 2026", checked:"Jul 23, 2026", status:"Static implementation and documentation reviewed", runtime:"Not independently runtime tested", repository:"CharmHealth/charm-mcp-server", website:"GitHub", packages:"Source repository", workflowFit:["Source-data inspection","Clinical workflow prototyping","EHR integration assessment"], capabilities:["17 documented patient and encounter tools","History, medications, allergies, diagnoses, vitals, and labs","Files, messaging, practice data, and task workflows"], limitation:"The tool surface includes clinical and administrative writes. Real patient use requires appropriate CharmHealth authorization, HIPAA-compliant infrastructure, access controls, audit logging, encryption, retention policy, and independent clinical validation.", url:"https://github.com/CharmHealth/charm-mcp-server" },
  { name:"health-record-mcp", kind:"MCP server", category:"Clinical Data & Interoperability", summary:"SMART-on-FHIR gateway that loads structured and unstructured EHR content and exposes read-oriented record analysis tools.", tags:["SMART on FHIR","EHR records","Read-only SQL"], added:"Jul 23, 2026", checked:"Jul 23, 2026", status:"Static implementation and documentation reviewed", runtime:"Not independently runtime tested", repository:"jmandel/health-record-mcp", website:"GitHub", packages:"health-record-mcp", workflowFit:["Patient-record exploration","FHIR extraction prototyping","Source-data quality review"], capabilities:["SMART App Launch and broad FHIR resource retrieval","Attachment text extraction","Read-only SQL with local stdio and experimental SSE modes"], limitation:"It is oriented to individual authorized records rather than population-scale RWE. SQL, attachment extraction, OAuth scope, PHI handling, and the experimental network mode require careful validation and governance.", url:"https://github.com/jmandel/health-record-mcp" },
  { name:"Medical Terminologies MCP", kind:"MCP server", category:"OMOP & terminology", summary:"Unified terminology server for ICD-10/11, LOINC, MeSH, RxNorm, ATC, UMLS-related mappings, and optional SNOMED workflows.", tags:["ICD / LOINC","RxNorm / MeSH","Crosswalks"], added:"Jul 23, 2026", checked:"Jul 23, 2026", status:"Static implementation and documentation reviewed", runtime:"Not independently runtime tested", repository:"SidneyBissoli/medical-terminologies-mcp", website:"Hosted + GitHub", packages:"medical-terminologies-mcp 1.5.0", workflowFit:["Phenotype specification","Code-set development","Cross-terminology review"], capabilities:["31 default tools and 37 with SNOMED enabled","Search, details, hierarchies, and mappings","Prompts, resources, hosted, and self-hosted transports"], limitation:"Terminology licensing, credentials, regional editions, version drift, and imperfect crosswalks can materially affect results. The project explicitly is not a clinical-care decision tool; code sets require expert review.", url:"https://github.com/SidneyBissoli/medical-terminologies-mcp" },
  { name:"MedRecPro Drug Label Server", kind:"MCP server + platform", category:"Regulatory & Product Data", summary:"Pharmaceutical label platform with an MCP gateway over FDA Structured Product Label data and an adverse-event risk dashboard.", tags:["FDA SPL","Drug labels","Safety dashboard"], added:"Jul 23, 2026", checked:"Jul 23, 2026", status:"Static implementation and documentation reviewed", runtime:"Not independently runtime tested", repository:"chriserikbarnes/MedRecPro", website:"GitHub", packages:"MedRecProMCP component", workflowFit:["Label evidence retrieval","Product characterization","Safety-signal context"], capabilities:["SPL ingestion and structured label search","Authenticated MCP access and label comparison","Orange Book imports and standardized adverse-event risk tables"], limitation:"This is a multi-component platform, not a simple read-only endpoint. Authentication, database deployment, source refreshes, label parsing, derived risk statistics, and any AI-generated synthesis require independent verification.", url:"https://github.com/chriserikbarnes/MedRecPro" },
  { name:"DoWhy MCP", kind:"MCP server", category:"Causal Inference & Analytics", summary:"MCP interface around DoWhy-oriented causal modeling, estimation, refutation, counterfactual, and discovery workflows.", tags:["DoWhy","Effect estimation","Sensitivity analysis"], added:"Jul 23, 2026", checked:"Jul 23, 2026", status:"Static implementation and documentation reviewed · caveat", runtime:"Not independently runtime tested", repository:"lesong36/dowhy_mcp", website:"GitHub", packages:"Source repository", workflowFit:["Causal model specification","Effect estimation","Sensitivity and refutation analysis"], capabilities:["42 documented tools spanning graphs and models","Estimation, counterfactuals, and causal influence","Root-cause, sensitivity, and discovery workflows"], limitation:"Repository documentation makes broad methodological claims and also records incomplete DoWhy feature coverage. Correct identification, estimator choice, diagnostics, and numerical behavior require method-level testing against known analyses.", url:"https://github.com/lesong36/dowhy_mcp" },
  { name:"StatsPAI", kind:"Python library + agent interface", category:"Causal Inference & Analytics", summary:"Agent-oriented Python econometrics and causal-inference library covering common Stata/R-style empirical research workflows.", tags:["Econometrics","Causal inference","Target trials"], added:"Jul 23, 2026", checked:"Jul 23, 2026", status:"Static implementation and documentation reviewed", runtime:"Not independently runtime tested", repository:"brycewang-stanford/StatsPAI", website:"GitHub", packages:"StatsPAI", workflowFit:["Observational effect estimation","Target-trial and epidemiologic analysis","Reproducible reporting"], capabilities:["Regression, IV, DiD, RD, synthetic control, and matching","Survival and epidemiology modules","Diagnostics, agent schemas, and publication export"], limitation:"The surface is unusually broad and optional dependencies vary by method. Agent-ready schemas and warnings do not establish identification or numerical correctness; each estimator and study-specific assumption needs independent validation.", url:"https://github.com/brycewang-stanford/StatsPAI" },
  { name:"CDISC Library MCP Server", kind:"MCP server", category:"Trials & Study Design", summary:"Task-oriented MCP wrapper for CDISC Library discovery, Biomedical Concepts, and SDTM Dataset Specializations.", tags:["CDISC Library","SDTM","Biomedical concepts"], added:"Jul 23, 2026", checked:"Jul 23, 2026", status:"Static implementation and documentation reviewed", runtime:"Not independently runtime tested", repository:"Cicatriiz/cdisc-library-mcp-server", website:"GitHub", packages:"cdisc-library-mcp-server", workflowFit:["Standards interpretation","CRF-to-SDTM planning","Reproducible standards lookup"], capabilities:["Search and suggestions","Latest and versioned Biomedical Concept packages","SDTM specializations, domains, package locking, caching, and retries"], limitation:"A CDISC Library subscription key is required. “Latest” routes can change over time, while package routes must be selected deliberately for reproducibility; returned standards artifacts still require qualified CDISC interpretation.", url:"https://github.com/Cicatriiz/cdisc-library-mcp-server" },
  { name:"CRF Annotation MCP", kind:"MCP server", category:"Trials & Study Design", summary:"Local MCP server for extracting and querying SDTM domain and variable annotations from annotated CRF PDFs.", tags:["Annotated CRF","SDTM mapping","PDF extraction"], added:"Jul 23, 2026", checked:"Jul 23, 2026", status:"Static implementation and documentation reviewed", runtime:"Not independently runtime tested", repository:"vikasgaddu1/crf-annotation-mcp", website:"GitHub", packages:"crf-annotation-mcp", workflowFit:["CRF review","SDTM mapping inspection","Standards traceability"], capabilities:["Reads FreeText annotations","Lists domains and variables","Locates CRF pages for SDTM content"], limitation:"It depends on annotation conventions and PDF structure and does not validate whether mappings are complete or correct. Sensitive study documents should remain under controlled local access.", url:"https://github.com/vikasgaddu1/crf-annotation-mcp" },
  { name:"omcp_kge", kind:"MCP server / knowledge graph", category:"OMOP & terminology", summary:"Biomedical-ontology knowledge graph with embeddings intended for OMOP MCP and agent-to-agent terminology workflows.", tags:["Knowledge graph","Embeddings","Biomedical ontologies"], added:"Jul 23, 2026", checked:"Jul 23, 2026", status:"Static documentation reviewed · limited evidence", runtime:"Not independently runtime tested", repository:"fastomop/omcp_kge", website:"GitHub", packages:"Source repository", workflowFit:["Concept discovery","Semantic terminology exploration","Mapping research"], capabilities:["Biomedical ontology knowledge graph","Embedding-based semantic exploration","OMOP-oriented agent workflow integration"], limitation:"Documentation is minimal and does not establish mapping accuracy, ontology/version coverage, update cadence, or production readiness. Treat semantic neighbors as candidates for expert review, not authoritative mappings.", url:"https://github.com/fastomop/omcp_kge" },
  { name:"RWE Life Sciences MCP", kind:"MCP server", category:"RWE Data & Analytics", summary:"Demonstration MCP tool returning aggregated cohort characteristics for a small synthetic real-world-evidence dataset.", tags:["Synthetic RWE","Cohort query","Demonstration"], added:"Jul 23, 2026", checked:"Jul 23, 2026", status:"Static implementation and documentation reviewed · demo", runtime:"Not independently runtime tested", repository:"soundarmoorthy/mcp_rwe", website:"GitHub", packages:"Source repository", workflowFit:["Cohort-query prototyping","RWE interface demonstrations","Educational feasibility review"], capabilities:["Condition-based cohort query","Demographic and metadata summaries","Documented ICD-10 context and caveats"], limitation:"All data are synthetically generated and the supported condition set is small. It does not establish fitness for production cohort discovery, patient-level analysis, data privacy controls, or clinical inference.", url:"https://github.com/soundarmoorthy/mcp_rwe" },
  { name:"EMA MCP", kind:"MCP server", category:"Regulatory & Product Data", summary:"Unofficial MCP wrapper for EMA public data covering medicines, documents, orphan designations, shortages, safety communications, and procedures.", tags:["EMA medicines","EPAR documents","EU safety"], added:"Jul 23, 2026", checked:"Jul 23, 2026", status:"Static implementation and documentation reviewed", runtime:"Not independently runtime tested", repository:"openpharma-org/ema-mcp", website:"GitHub", packages:"ema-mcp-server", workflowFit:["EU product evidence","Regulatory context","Safety and supply monitoring"], capabilities:["Medicine search and details","Orphan designations, shortages, and referrals","Post-authorization procedures, DHPCs, and document search"], limitation:"This is an unofficial wrapper over changing public APIs. Coverage, field semantics, pagination, document completeness, and regulatory currency must be checked against authoritative EMA records before decision use.", url:"https://github.com/openpharma-org/ema-mcp" },
  { name:"FDA MCP", kind:"MCP server", category:"Regulatory & Product Data", summary:"Unofficial FDA intelligence server combining openFDA drug data with locally cached Orange Book and Purple Book datasets.", tags:["openFDA","Orange Book","Purple Book"], added:"Jul 23, 2026", checked:"Jul 23, 2026", status:"Static implementation and documentation reviewed", runtime:"Not independently runtime tested", repository:"openpharma-org/fda-mcp", website:"GitHub", packages:"fda-mcp-server", workflowFit:["Product and label context","Safety-case research","Approval and competition landscape"], capabilities:["Drug lookup, labels, FAERS, approvals, recalls, and shortages","Orange Book patents, exclusivity, and equivalence","Purple Book biologics and biosimilars"], limitation:"OpenFDA reports do not establish incidence or causality, and cached Orange/Purple Book data must be refreshed and reconciled. The broad regulatory surface requires endpoint-level provenance and primary-record confirmation.", url:"https://github.com/openpharma-org/fda-mcp" },
  { name:"Claude Skills for Epidemiology Researchers", kind:"Skill collection", category:"Literature & Evidence Synthesis", summary:"Two lightweight skills for structured clinical-research queries and methods-aware critical appraisal by epidemiology researchers.", tags:["Critical appraisal","Epidemiology","Bias review"], added:"Jul 23, 2026", checked:"Jul 23, 2026", status:"Static documentation reviewed", runtime:"Not independently runtime tested", repository:"NancyNSH/Claude-Skills-for-Epidemiology-Researchers", website:"GitHub", packages:"Two Claude skills", workflowFit:["Literature question framing","Critical appraisal","Bias and methods review"], capabilities:["Clinical Research Query skill for evidence, gaps, and instruments","Epi Paper Reader for confounding and selection bias","Measurement-bias and statistical-method critique"], limitation:"The skills structure model responses but do not retrieve or validate sources on their own. Completeness, citation accuracy, domain fit, and appraisal judgments depend on the connected model and evidence supplied.", url:"https://github.com/NancyNSH/Claude-Skills-for-Epidemiology-Researchers" },
  { name:"MediStat Table 1", kind:"Skill + analysis scripts", category:"Causal Inference & Analytics", summary:"Clinical-research skill that generates publication-oriented baseline-characteristics tables from CSV or Excel data with study-design-aware rules.", tags:["Table 1","Baseline balance","SMD"], added:"Jul 23, 2026", checked:"Jul 23, 2026", status:"Static implementation and documentation reviewed", runtime:"Not independently runtime tested", repository:"JeonKH81/MediStat-Table1", website:"GitHub", packages:"clinical-table1 skill", workflowFit:["Cohort description","Baseline balance review","Manuscript table production"], capabilities:["RCT and observational policies","SMD-first summaries, p-values, and multiple-testing warnings","HTML, Word, and LaTeX outputs with identifier exclusion"], limitation:"It is limited to Table 1 workflows and explicitly excludes survival and mixed-effects analyses. Automatic identifier detection is heuristic, so PHI review, variable typing, missingness handling, and statistical output require verification.", url:"https://github.com/JeonKH81/MediStat-Table1" },
  { name:"ClinicalTrials.gov MCP Server", kind:"MCP server", category:"Trials & Study Design", summary:"ClinicalTrials.gov API v2 server for trial discovery, record and results retrieval, landscape analysis, and preliminary eligibility matching.", tags:["ClinicalTrials.gov","Trial results","Eligibility"], added:"Jul 23, 2026", checked:"Jul 23, 2026", status:"Static implementation and documentation reviewed", runtime:"Not independently runtime tested", repository:"cyanheads/clinicaltrialsgov-mcp-server", website:"Hosted + GitHub", packages:"clinicaltrialsgov-mcp-server 2.8.2", workflowFit:["Trial landscape review","Comparator and endpoint research","External evidence context"], capabilities:["Seven tools for search, counts, field definitions, and complete records","Posted results retrieval","Preliminary eligibility matching with stdio and HTTP transports"], limitation:"Registry records can be incomplete, outdated, or lack results. Eligibility matching is an automated pre-screen, not a clinical determination, and patient details should not be sent to an unapproved hosted endpoint.", url:"https://github.com/cyanheads/clinicaltrialsgov-mcp-server" },
  { name:"FHIR MCP Server (WSO2)", kind:"MCP server", category:"Clinical Data & Interoperability", summary:"General FHIR API bridge supporting SMART-on-FHIR authentication, multiple MCP transports, FHIRPath filtering, and read/write interactions.", tags:["FHIR API","SMART on FHIR","FHIRPath"], added:"Jul 23, 2026", checked:"Jul 23, 2026", status:"Static implementation and documentation reviewed", runtime:"Not independently runtime tested", repository:"wso2/fhir-mcp-server", website:"GitHub", packages:"fhir-mcp-server", workflowFit:["FHIR source inspection","Interoperability prototyping","Clinical-data pipeline assessment"], capabilities:["Capability discovery, search, and read","Create, update, delete, and authenticated-user lookup","Stdio, SSE, HTTP, OAuth, and FHIRPath response filtering"], limitation:"Create, update, and delete can change clinical systems. Authorization may be disabled for local demos, and Docker authorization has documented caveats; production use requires strict scopes, audit controls, PHI safeguards, and server-specific validation.", url:"https://github.com/wso2/fhir-mcp-server" },
  { name:"RxNorm MCP", kind:"MCP server", category:"OMOP & terminology", summary:"Small MCP wrapper around the free NLM RxNav REST API for RxNorm medication terminology access.", tags:["RxNorm","RxNav","Medication coding"], added:"Jul 23, 2026", checked:"Jul 23, 2026", status:"Static implementation and documentation reviewed · limited evidence", runtime:"Not independently runtime tested", repository:"pipeworx-io/mcp-rxnorm", website:"Hosted + GitHub", packages:"mcp-rxnorm", workflowFit:["Medication normalization","Drug concept lookup","Code-set development"], capabilities:["Hosted MCP endpoint","RxNorm and RxNav query tools","Natural-language routing through the publisher gateway"], limitation:"Documentation is sparse and does not fully enumerate tool schemas, caching, error handling, or terminology-version behavior. RxNorm matches and relationships require source-level verification before phenotype or medication-class use.", url:"https://github.com/pipeworx-io/mcp-rxnorm" },
  { name:"PubMed MCP Server (Cyanheads)", kind:"MCP server", category:"Literature & Evidence Synthesis", summary:"Biomedical literature server spanning PubMed, PubMed Central, Europe PMC, MeSH, related articles, citations, and open-full-text retrieval.", tags:["PubMed / PMC","Europe PMC","MeSH"], added:"Jul 23, 2026", checked:"Jul 23, 2026", status:"Static implementation and documentation reviewed", runtime:"Not independently runtime tested", repository:"cyanheads/pubmed-mcp-server", website:"Hosted + GitHub", packages:"@cyanheads/pubmed-mcp-server 2.9.8", workflowFit:["Literature discovery","Query refinement","Citation and full-text retrieval"], capabilities:["Ten tools for search, metadata, full text, and citations","Related records, spelling, MeSH, and citation matching","Identifier conversion with hosted and self-hosted transports"], limitation:"Full text is limited by PMC, Europe PMC, and Unpaywall availability and licensing. Reproducible reviews still require logged queries, dates, deduplication, screening, evidence grading, and verification of citations and extracted content.", url:"https://github.com/cyanheads/pubmed-mcp-server" },
  { name:"Pharmaceutical & Bioequivalence Intelligence MCP", kind:"MCP server", category:"Pharmacovigilance & safety", summary:"Multi-source pharmaceutical intelligence server for drug records, interactions, FAERS adverse events, WHO, TGA, FDA NDI, and ChEMBL context.", tags:["Drug safety","FAERS","Interactions"], added:"Jul 23, 2026", checked:"Jul 23, 2026", status:"Static implementation and documentation reviewed · caveat", runtime:"Not independently runtime tested", repository:"rootsbymenda/pharma-mcp-server", website:"GitHub", packages:"pharma-regulatory", workflowFit:["Safety-case research","Drug and interaction context","Regulatory evidence scoping"], capabilities:["Drug lookup and interaction checks","FAERS adverse-event summaries","Cross-source pharmaceutical search with source links"], limitation:"The repository describes bounded local datasets for several sources, including a small FAERS subset, so results are not comprehensive or incidence estimates. Interaction severity and management text require clinical and primary-source verification.", url:"https://github.com/rootsbymenda/pharma-mcp-server" },
];

function CardPrototype() {
  const [expanded, setExpanded] = useState<string | null>(null);
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("All categories");
  const categories = useMemo(() => [...new Set(prototypeCards.map(card => card.category))], []);
  const results = useMemo(() => prototypeCards.filter(card => {
    const needle = query.trim().toLowerCase();
    const haystack = [card.name, card.kind, card.category, card.summary, card.status, ...card.tags, ...card.workflowFit, ...card.capabilities].join(" ").toLowerCase();
    return (!needle || haystack.includes(needle)) && (category === "All categories" || card.category === category);
  }), [query, category]);
  return <section className="card-prototype" aria-label="Reviewed registry catalogue">
    <div className="review-controls"><label className="search-box"><span aria-hidden="true">⌕</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search ‘FAERS’, ‘PubMed’, ‘OMOP’…" aria-label="Search reviewed catalogue" /></label><label><span>Category</span><select value={category} onChange={e => setCategory(e.target.value)}>{["All categories", ...categories].map(option => <option key={option}>{option}</option>)}</select></label></div>
    <div className="prototype-list">{results.map((card) => { const open = expanded === card.name; return <article className={`prototype-card ${open ? "is-open" : ""}`} key={card.name}>
      <button className="prototype-summary" onClick={() => setExpanded(open ? null : card.name)} aria-expanded={open}>
        <div><span className="prototype-type">{card.kind} · {card.category}</span><strong>{card.name} {"favorite" in card && card.favorite ? <span className="favorite-star" title="Black Swan Causal Labs favorite" aria-label="Black Swan Causal Labs favorite">★</span> : null}</strong><p>{card.summary}</p><div className="tags">{card.tags.map(tag => <span key={tag}>{tag}</span>)}</div></div>
        <div className="prototype-freshness"><span>Added {card.added}</span><span>Checked {card.checked}</span><b>{open ? "Close −" : "View RWE uses +"}</b></div>
      </button>
      {open && <div className="prototype-details"><div className="capability-panel"><span>RWE workflow fit</span><div className="workflow-tags">{card.workflowFit.map(item => <b key={item}>{item}</b>)}</div><span>Documented capabilities</span><ul>{card.capabilities.map(capability => <li key={capability}>{capability}</li>)}</ul><p><b>Limitation</b> {card.limitation}</p></div><dl><div><dt>Status</dt><dd>{card.status}</dd></div><div><dt>Runtime</dt><dd>{card.runtime}</dd></div><div><dt>Repository</dt><dd>{card.repository}</dd></div><div><dt>Website</dt><dd>{card.website}</dd></div><div><dt>Packages</dt><dd>{card.packages}</dd></div></dl><a className="prototype-link" href={card.url} target={card.url === "#" ? undefined : "_blank"} rel="noreferrer">Open source ↗</a></div>}
    </article>; })}</div>
    {!results.length && <div className="empty"><span>∅</span><h3>No reviewed match.</h3><p>Try a broader source, method, or workflow term.</p><button onClick={() => { setQuery(""); setCategory("All categories"); }}>Clear filters</button></div>}
  </section>;
}

function Filter({ label, value, options, setValue, display = (v: string) => v }: { label: string; value: string; options: string[]; setValue: (v: string) => void; display?: (v: string) => string }) {
  return <label><span>{label}</span><select value={value} onChange={(e) => setValue(e.target.value)}>{options.map((option) => <option key={option} value={option}>{display(option)}</option>)}</select></label>;
}

function EntryCard({ item, number }: { item: Entry; number: number }) {
  return <article className={`entry-card tier-${item.tier.toLowerCase()}`}>
    <div className="card-index">{String(number).padStart(2, "0")}</div>
    <div className="card-main">
      <div className="card-meta"><span>{item.category}</span><span>{item.kind}</span></div>
      <h3><a href={item.url} target="_blank" rel="noreferrer">{item.name} <span>↗</span></a></h3>
      <p className="org">{item.org}</p><p className="summary">{item.summary}</p>
      <div className="tags">{item.tags.slice(0, 4).map((tag) => <span key={tag}>{tag}</span>)}</div>
      {item.note && <p className="caveat"><b>Editorial note</b> {item.note}</p>}
    </div>
    <div className="card-evidence">
      <div className={`verification-badge ${item.verification.status === "Unavailable" ? "unavailable" : ""}`}><span>{item.verification.status === "Metadata verified" ? "Repository checked" : "Repository unavailable"}</span><small>{formatDate(item.verification.verifiedAt)}</small></div>
      <div className="tier-badge"><span>Editorial classification</span><b>{tierCopy[item.tier]?.label}</b><small>{tierCopy[item.tier]?.description}</small></div>
      <dl><div><dt>Repository</dt><dd>{item.verification.repositoryStatus}</dd></div><div><dt>Last push</dt><dd>{item.lastPush ? formatDate(item.lastPush) : "Not available"}{item.stale && <em>stale</em>}</dd></div><div><dt>License</dt><dd>{item.verification.license ?? "Not available"}</dd></div><div><dt>Official registry</dt><dd>{item.verification.officialRegistryListed ? `${item.verification.officialRegistryName} ${item.verification.officialRegistryVersion}` : "No exact URL match"}</dd></div><div><dt>Sources</dt><dd>{item.dataSources.join(", ")}</dd></div><div><dt>Stars</dt><dd>{item.stars}</dd></div></dl>
    </div>
  </article>;
}
